version: "3"
services:
  nginx5:
    image: nginx
    ports:
     - "3000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - node-app

  node-app:
    build: .
    image: audriusj/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=audrius
      - MONGO_INITDB_ROOT_PASSWORD=Slaptazodis04
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:3

volumes:
  mongo-db: